
logging.level.root=info

spring.messages.basename=errors

server.servlet.session.tracking-modes=cookie
server.servlet.session.timeout=600

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://diy-database.cnkcmg4igmw7.ap-northeast-2.rds.amazonaws.com:3306
spring.datasource.username=adminDiy
spring.datasource.password=passworddiy


spring.redis.host=127.0.0.1
spring.redis.password=
spring.redis.port=6379

mybatis.type-aliases-package=project.DIY.domain
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.jdbc-type-for-null=null

spring.mvc.static-path-pattern=/resources/static/**

mail.smtp.auth=true
mail.smtp.starttls.required=true
mail.smtp.starttls.enable=true
mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
mail.smtp.socketFactory.fallback=false
mail.smtp.port=465
mail.smtp.socketFactory.port=465
server.servlet.session.cookie.http-only=false

AdminMail.id=humanedu6.4@gmail.com
AdminMail.password=ytbmpnksuamlxnyg


spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB